
package mypackage;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonWebService", targetNamespace = "http://lab1.wst.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonWebService {


    /**
     * 
     * @return
     *     returns java.util.List<mypackage.Person>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://lab1.wst.com/", className = "mypackage.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://lab1.wst.com/", className = "mypackage.GetPersonsResponse")
    @Action(input = "http://lab1.wst.com/PersonWebService/getPersonsRequest", output = "http://lab1.wst.com/PersonWebService/getPersonsResponse")
    public List<Person> getPersons();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<mypackage.Human>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHumans2", targetNamespace = "http://lab1.wst.com/", className = "mypackage.GetHumans2")
    @ResponseWrapper(localName = "getHumans2Response", targetNamespace = "http://lab1.wst.com/", className = "mypackage.GetHumans2Response")
    @Action(input = "http://lab1.wst.com/PersonWebService/getHumans2Request", output = "http://lab1.wst.com/PersonWebService/getHumans2Response")
    public List<Human> getHumans2(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<mypackage.Human>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHumans", targetNamespace = "http://lab1.wst.com/", className = "mypackage.GetHumans2")
    @ResponseWrapper(localName = "getHumansResponse", targetNamespace = "http://lab1.wst.com/", className = "mypackage.GetHumans2Response")
    @Action(input = "http://lab1.wst.com/PersonWebService/getHumansRequest", output = "http://lab1.wst.com/PersonWebService/getHumansResponse")
    public List<Human> getHumans(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
